### ISSUE TITLE
デプロイ環境の調査

### ISSUE THREAD

**Issue by ltoppyl** [hacku-2022-kari/gamename-back-end#142]
## ✨ 概要

- 現状、環境変数の設定周りの関係で、Private のレポジトリに差分を移して、GitHub Actions を使用して fiber を使ってデプロイしている
- デプロイ環境を見直して、どうすれば、このレポジトリの差分をしっかり自動的に反映させられるかを調べる

## 🔥 ゴール

- このレポジトリの状態からデプロイできる方法がわかる (実施は別 Issue でも可)

## ✅ タスク

- [ ] 今デプロイしている状態をこのレポジトリからできないかを調査する
- [ ] GitHub Actions を使用して、他にデプロイができないかを調査
- [ ] Firebase や GCP を使ってデプロイできないかを調査

**Comment by fukamikensuke** [comment]
detaでデプロイしてみたけど、何故か手元でしかうまくいかない

**Comment by ltoppyl** [comment]
DETA Space は API のエンドポイントとしてはデプロイできなくなってそう
https://qiita.com/kakiuchis/items/80f6239f6319066ee18d

**Comment by ltoppyl** [comment]
Firebase 
- Cloud Functions は公式には Go のデプロイはサポートされていない (やりかたはあるっぽいが)
- Cloud Functions は無料枠に含まれない

**Comment by fukamikensuke** [comment]
Deta.spaceはいける
```
presets:
      api_keys: true
    public_routes:
      - "/*"
 
```
この二行をspacefile必要
一行目でアプリのユーザーがプログラムでアプリインスタンスにアクセスできるようにするには、アプリでMicrosのプリセットを有効にする
[public_routes]で公開するものの選定を行う。"*"が"/"以下はなんでも行けるようにする。
"create/*","read/*"などで本来使うが今回は全部使うから"/*"でよい。
あとはこれを本来のやつでデプロイできるようにする

**Comment by fukamikensuke** [comment]
#152 でdeta.spaceにてデプロイで行ったためclose
