### ISSUE TITLE
DB 設計

### ISSUE THREAD

**Issue by ltoppyl** [hacku-2022-kari/gamename-back-end#2]
## ✨ 概要
- DB 設計

## 🔥 ゴール

- DB 設計が完了している

## 📄 参考資料

- xxx

## ✅ タスク

- [ ] xxx

**Comment by fukamikensuke** [comment]
![image](https://user-images.githubusercontent.com/77095417/218896825-059bc40e-f224-466d-8bf7-640f175b7e11.png)

**Comment by ltoppyl** [comment]
完了したため close
