### ISSUE TITLE
エラーハンドリングを行う

### ISSUE THREAD

**Issue by fukamikensuke** [hacku-2022-kari/gamename-back-end#44]
## 🐛 概要
エラーハンドリングを考慮しての実装
## 👀 再現手順

1. xxx
2. xxx
3. xxx

## 📦️ 環境

- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge

## ✅ タスク

- [ ] xxx

**Comment by fukamikensuke** [comment]
-  一人でプレイするときにプレイできてしまう

**Comment by ltoppyl** [comment]
再現できないため一旦 close
