### ISSUE TITLE
バックエンドのデプロイ

### ISSUE THREAD

**Issue by fukamikensuke** [hacku-2022-kari/gamename-back-end#63]
## ✨ 概要

- バックエンドのデプロイをし、触れるようにする。

## 🔥 ゴール

- xxx

## 📄 参考資料

- xxx

## ✅ タスク

- [ ] xxx

**Comment by ltoppyl** [comment]
これは完了でよいのでは！？

**Comment by fukamikensuke** [comment]
確かに
